@extends('layouts.site-layout') @section('content')
<section class="border-bottom" id="about">
  <div class="container px-5 my-5">
    <div class="row gx-4 gx-lg-5">
      <div class="col-md-12">
        <h1 class="mt-5 text-center">Payouts</h1>
        <h5 class="text-center"><b>90% Payback</b></h5>
        <h5 class="text-center"><b>Remaining Funds From Each Regional Qualifier Forward To National Championship</b></h5>
        <h5 class="text-center"><b>All Advertised Payouts Based On Participation</b></h5>
        <table class="table table-bordered table-hover" style="font-weight:bold;text-align:center">
          <thead>
            <tr>
              <th>Position</th>
              <th>Payout</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>$100,000.00</td>
            </tr>
            <tr>
              <td>2</td>
              <td>$25,000.00</td>
            </tr>
            <tr>
              <td>3</td>
              <td>$15,000.00</td>
            </tr>
            <tr>
              <td>4</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>5</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>6</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>7</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>8</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>9</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>10</td>
              <td>$10,000.00</td>
            </tr>
            <tr>
              <td>11</td>
              <td>$5,000.00</td>
            </tr>
            <tr>
              <td>12</td>
              <td>$5,000.00</td>
            </tr>
            <tr>
              <td>13</td>
              <td>$5,000.00</td>
            </tr>
            <tr>
              <td>14</td>
              <td>$5,000.00</td>
            </tr>
            <tr>
              <td>15</td>
              <td>$5,000.00</td>
            </tr>
            <tr>
              <td>16</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>17</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>18</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>19</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>20</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>21</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>22</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>23</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>24</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>25</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>26</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>27</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>28</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>29</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>30</td>
              <td>$3,000.00</td>
            </tr>
            <tr>
              <td>31</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>32</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>33</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>34</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>35</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>36</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>37</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>38</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>39</td>
              <td>$2,000.00</td>
            </tr>
            <tr>
              <td>40</td>
              <td>$2,000.00</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  </div>
</section>
@stop